spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/position_campaign
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update  # 데이터 유지하면서 스키마만 업데이트
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        format_sql: true
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: never  # 초기화 스크립트 비활성화 (JPA가 스키마 관리)
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      continue-on-error: true

server:
  port: 8080
  servlet:
    context-path: /

app:
  jwt:
    secret: myVeryLongAndSecureSecretKeyForJWTTokenGeneration123456789012345678901234567890
    expiration: 86400000 # 24 hours
    cookie-name: auth-token

cors:
  allowed-origins:
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true
